Public Class RubiksCube(){
  private int cubeState[6][8];
  //stores an array of numbers to track the sides of the rubiks cube.
  private int numTurn = 0;
  private int size = 2;
  public void initializeCube(){
    //sets the cubeState to a solved Cube with a nested for loop. Also sets unused space to a value of -1.
  }
  public void cycle(int hold){
    if (hold == 0){
      // cycles the values representing the face of the cube that is just cycling the same four numbers/colors.
    }
    // make more conditionals depending on which type of the 12 possible turns we make.
  }
  public void rotateTopC(){
    
  }

  

}
